PREFIX databus: <https://dataid.dbpedia.org/databus#>

CONSTRUCT {
  ?artifact ?p ?o .
  ?artifact databus:hasVersion ?version .
}
WHERE {
  VALUES ?artifact { <%RESOURCE_URI%> }

  GRAPH ?gArtifact {
    ?artifact ?p ?o .
  }

  OPTIONAL {
    GRAPH ?gVersion {
      ?version databus:artifact ?artifact .
    }
  }
}
