PREFIX databus: <https://dataid.dbpedia.org/databus#>

CONSTRUCT {
  ?group ?p ?o .
  ?group databus:hasArtifact ?artifact .
}
WHERE {
  VALUES ?group { <%RESOURCE_URI%> }

  GRAPH ?gGroup {
    ?group ?p ?o .
  }

  OPTIONAL {
    GRAPH ?gArtifact {
      ?artifact databus:group ?group .
    }
  }
}
